# Pandas

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
pd.Series([1,2,3,'mehr',0,-1])

0       1
1       2
2       3
3    mehr
4       0
5      -1
dtype: object

In [7]:
dates = pd.date_range("20210101" , periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(6 , 4)

array([[-0.73211715, -1.81773825,  0.70087814,  0.44686277],
       [ 0.82162285, -0.98065134, -0.38901737, -0.81385906],
       [-0.97679911, -1.1175753 ,  0.31273004, -0.33028873],
       [-1.47435487,  0.18718366,  0.34724882, -0.03491243],
       [-0.87593468, -1.06741351,  1.7459262 , -2.99734331],
       [-0.05641093, -1.67799834, -0.37909001, -1.36259441]])

In [14]:
df = pd.DataFrame(np.random.randn(6,4) , index=dates,columns=['A' , 'B' , 'C' , 'D'])
df

                   A         B         C         D
2021-01-01 -0.008397 -0.741906  0.111645 -0.353104
2021-01-02  0.927121 -0.634353 -0.019853 -1.651453
2021-01-03  0.676498  0.525098  0.682848 -0.203777
2021-01-04 -0.788965  0.049075  0.006745 -0.290602
2021-01-05 -0.288671 -0.976955 -1.017579  0.288137
2021-01-06 -2.694749 -0.569286 -0.724284 -0.244325

In [16]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [17]:
df.head

<bound method NDFrame.head of                    A         B         C         D
2021-01-01 -0.008397 -0.741906  0.111645 -0.353104
2021-01-02  0.927121 -0.634353 -0.019853 -1.651453
2021-01-03  0.676498  0.525098  0.682848 -0.203777
2021-01-04 -0.788965  0.049075  0.006745 -0.290602
2021-01-05 -0.288671 -0.976955 -1.017579  0.288137
2021-01-06 -2.694749 -0.569286 -0.724284 -0.244325>

In [18]:
df.tail(2)

                   A         B         C         D
2021-01-05 -0.288671 -0.976955 -1.017579  0.288137
2021-01-06 -2.694749 -0.569286 -0.724284 -0.244325

In [19]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.362860 -0.391388 -0.160080 -0.409187
std    1.303437  0.563983  0.614082  0.650549
min   -2.694749 -0.976955 -1.017579 -1.651453
25%   -0.663892 -0.715018 -0.548176 -0.337478
50%   -0.148534 -0.601819 -0.006554 -0.267463
75%    0.505274 -0.105515  0.085420 -0.213914
max    0.927121  0.525098  0.682848  0.288137

In [20]:
df.mean()

A   -0.362860
B   -0.391388
C   -0.160080
D   -0.409187
dtype: float64

In [21]:
df["A"].mean

<bound method Series.mean of 2021-01-01   -0.008397
2021-01-02    0.927121
2021-01-03    0.676498
2021-01-04   -0.788965
2021-01-05   -0.288671
2021-01-06   -2.694749
Freq: D, Name: A, dtype: float64>

In [22]:
df.T

   2021-01-01  2021-01-02  2021-01-03  2021-01-04  2021-01-05  2021-01-06
A   -0.008397    0.927121    0.676498   -0.788965   -0.288671   -2.694749
B   -0.741906   -0.634353    0.525098    0.049075   -0.976955   -0.569286
C    0.111645   -0.019853    0.682848    0.006745   -1.017579   -0.724284
D   -0.353104   -1.651453   -0.203777   -0.290602    0.288137   -0.244325

In [24]:
df[df["A"]>0]

                   A         B         C         D
2021-01-02  0.927121 -0.634353 -0.019853 -1.651453
2021-01-03  0.676498  0.525098  0.682848 -0.203777

# Read and write operation

In [26]:
! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

In [28]:
df.to_excel("my_data.xlsx" , index=True)